---
- name: Check if certificate already exists.
  ansible.builtin.stat:
    path: "{{ __ssl_domain_path }}/cert.pem"
  register: __ssl_letsencrypt_cert

- name: Generate and sign the certificate
  when: not __ssl_letsencrypt_cert.stat.exists
  containers.podman.podman_container:
    name: certbot-create-{{ ssl_domain | regex_replace("[^A-Za-z0-9]", "-") }}
    image: "{{ ssl_certbot_container_image }}"
    command: certonly {{ __ssl_certbot_params }}
    state: started
    user: root
    rm: true
    volumes: "{{ __ssl_certbot_volumes }}"
  become_user: "{{ __ssl_certbot_username }}"

- name: Wait until the cert file is present before continuing
  ansible.builtin.wait_for:
    path: "{{ __ssl_domain_path }}/cert.pem"
    state: present
    sleep: 10
    timeout: 120
