---
# Google DNS credentials
# Content of json file with Google secrets, typically load from file using:
# certbot_google_json_secret: {{lookup('file', 'letsencrypt-admin.json') }}
ssl_credentials_google: ""
ssl_letsencrypt_email: "user@example.com"
ssl_domain: "example.com"
ssl_certificate_name: "{{ ssl_domain | replace('*.', '') }}"

ssl_certbot_container_image: "docker.io/certbot/dns-google:arm64v8-latest"

# System user name of user managing certificates on letsencrypt host
ssl_certbot_username: certbot
