---
# vars file for ssl_common_vars

__ssl_credentials_path: "/srv/certs/.secret"
__ssl_letsencrypt_path: "/var/letsencrypt"
__ssl_credentials_google_filename: "letsencrypt-dns-admin.json"
__ssl_certbot_username: "certbot"

__ssl_certbot_user_homedir: /var/home/certbot
__ssl_certbot_systemd_dir: "{{ __ssl_certbot_user_homedir }}/.local/share/systemd/user/"
__ssl_systemd_container_prefix: "container"

__ssl_certificate_name: "{{ ssl_domain | replace('*.', '') }}"
__ssl_domain_path: "{{ __ssl_letsencrypt_path }}/live/{{ __ssl_certificate_name }}"

__ssl_certbot_params: >-
  --dns-google -m {{ ssl_letsencrypt_email }}
  --agree-tos --non-interactive
  --dns-google-credentials /secrets/{{ __ssl_credentials_google_filename }}
  --cert-name {{ __ssl_certificate_name }}
  -d {{ ssl_domain }}

__ssl_certbot_volumes:
  - "{{ __ssl_letsencrypt_path }}:/etc/letsencrypt:z"
  - "{{ __ssl_credentials_path }}:/secrets:z"
